version: '3'

services:
  html-to-pdf:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
    command: npm run dev 